version: 0.2
env:
    variables:
       rest_api_host: test.com
    
phases:
  install:
    runtime-versions:
      java: corretto11
      
    commands:
      echo 'build started'
      
  build:
     commands: 
       - echo 'build started'
       - echo '${CODEBUILD_START_TIME}'
       - echo '$CODEBUILD_START_TIME'
       - aws s3 cp s3://$BUILD_BUCKET/test.sh .
       - chmod +x test.sh
       - echo 'test file completed'
  post_build:
     commands: 
     
        - echo post build

      
      
      
