version: 0.2
env:
    variables:
       rest_api_host: test.com
    
phases:
  install:
    runtime-versions:
      java: corretto11
      
    commands:
      echo 'build started'
      
  build:
     commands: 
       - echo 'build started'
       
       - echo $CODEBUILD_START_TIME
       - echo $CODEBUILD_END_TIME
       - echo $CODEBUILD_BUILD_SUCCEEDING
       - echo  $CODEBUILD_BUILD_SUCCEEDING
       - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
       - echo COMMITTER_DATE
       - aws codepipeline  list-action-executions --pipeline-name TestAPI  --region us-east-2 --max-items 1
       - aws codepipeline get-pipeline-execution --pipeline-name TestAPI --pipeline-execution-id 57f0a6aa-3b6f-4966-a473-e94f0dcfe90a
       - aws s3 cp s3://achal1/test.sh .
       - chmod +x test.sh
       - ./test.sh
       - echo 'test file completed '
  post_build:
     commands: 
     
        - echo "post build "

      
      
      
